stages:
  - build
  - test
  - deploy

before_script:
#  - export PATH=$HOME/bin:/usr/local/bin:/usr/bin:/bin
  - pwd
  - whoami
  - rvm gemset use InRailsWeBlog
  - ruby -v

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - vendor/bundle

build:
  stage: build
  script:
    - gem install bundler --no-ri --no-rdoc
    - bundle install --quiet --path=vendor/bundle --binstubs vendor/bundle/bin --jobs $(nproc) "${FLAGS[@]}"

audit:
  stage: test
  script:
    - gem install bundler-audit
    - bundle audit check --update
  allow_failure: true

brakeman:
  stage: test
  script:
    - bundle exec brakeman -q
  allow_failure: true

missing_translations:
  stage: test
  script:
    - bundle exec i18n-tasks missing

test:
  stage: test
  variables:
    RAILS_ENV: 'test'
    DATABASE_TEST_NAME: 'inrailsweblog_test'
    DATABASE_TEST_USERNAME: 'inrailsweblog_test'
    DATABASE_TEST_PASSWORD: 'inrailsweblog'
  script:
    - bundle exec rails db:drop RAILS_ENV=test
    - bundle exec rails db:create RAILS_ENV=test
    - bundle exec rails db:schema:load RAILS_ENV=test
    - bundle exec rspec -t basic spec/

deploy:
  stage: deploy
  script:
    - bundle exec rails InRailsWeBlog:deploy NO_TEST=true
  environment:
    name: production
    url: https://www.inrailsweblog.com
  only:
    - master
