Documentation:
  Enabled: false

LineLength:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'node_modules/**/*'

##################### Metrics ##################################
Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be a Fixnum or a Float.
  Max: 60

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 400

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 120

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockNesting:
  Max: 4

Style/ExtraSpacing:
  AllowForAlignment: true

Style/RedundantSelf:
  Enabled: false

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/FirstParameterIndentation:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/LeadingCommentSpace:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/IndentHash:
  Enabled: false

Style/MultilineBlockLayout:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/SpaceInLambdaLiteral:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
