# Global dynamic variables
# Static variables are defined in: config/settings/application.rb
# These variables can be changed in application
defaults: &defaults
  # Default per page
  per_page: 20

  # Search results per page
  search_per_page: 30

  # Maximum upload image size
  image_size: <%= 8.megabytes %>

  # Default for Topics
  topic_color: "#e5e5e5"

  # Default for Tags
  tag_color: "#e5e5e5"

  # Screen size
  small_screen: 600
  small_screen_up: 601
  medium_screen: 992
  medium_screen_up: 993
  large_screen: 1200
  large_screen_up: 1201

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
