development:
  adapter: postgresql
  encoding: unicode
  database: inrailsweblog_dev
  host: localhost
  pool: 15
  username: <%= ENV['DATABASE_DEV_USERNAME'] %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: inrailsweblog_test
  host: localhost
  pool: 15
  username: <%= ENV['DATABASE_TEST_USERNAME'] %>
  password: <%= ENV['DATABASE_TEST_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: inrailsweblog
  host: localhost
  pool: 15
  connect_timeout: 30
  variables:
    statement_timeout: 2000
  username: <%= ENV['DATABASE_PROD_USERNAME'] %>
  password: <%= ENV['DATABASE_PROD_PASSWORD'] %>
