development:
  adapter: postgresql
  encoding: unicode
  database: inrailsweblog_dev
  pool: 15
  username: <%= ENV['DATABASE_DEV_USERNAME'] %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: inrailsweblog_test
  pool: 15
  username: <%= ENV['DATABASE_TEST_USERNAME'] %>
  password: <%= ENV['DATABASE_TEST_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: inrailsweblog
  pool: 15
  username: <%= ENV['DATABASE_PROD_USERNAME'] %>
  password: <%= ENV['DATABASE_PROD_PASSWORD'] %>
