fallbacks: true
js_extend: false
sort_translation_keys: false

export_i18n_js: 'app/assets/javascripts/modules'

translations:
- file: 'public/assets/home-%{locale}.js'
  only: ['*.js.helpers.*', '*.js.date.*', '*.js.cookies.*', '*.js.views.home.*', '*.js.views.header.*', '*.js.views.sidebar.*', '*.js.views.footer.*', '*.js.topic.*', '*.js.article.*', '*.js.tag.*', '*.js.user.*', '*.js.search.*', '*.js.comment.*', '*.js.bookmark.*', '*.js.checkbox.*', '*.js.languages.*']

- file: 'public/assets/articles/show-%{locale}.js'
  only: ['*.js.helpers.*', '*.js.date.*', '*.js.cookies.*', '*.js.views.header.*', '*.js.views.footer.*', '*.js.search.modal.*', '*.js.topic.*', '*.js.article.*', '*.js.tag.*', '*.js.user.*', '*.js.search.*', '*.js.bookmark.*', '*.js.comment.*']
- file: 'public/assets/articles/new-%{locale}.js'
  only: ['*.js.helpers.*', '*.js.date.*', '*.js.cookies.*', '*.js.views.header.*', '*.js.views.footer.*', '*.js.search.modal.*', '*.js.topic.*', '*.js.article.*', '*.js.tag.*', '*.js.user.*', '*.js.search.*', '*.js.bookmark.*', '*.js.comment.*', '*.js.form.*', '*.js.drop_zone.*', '*.js.selecter.*', '*.js.categorized_tag.*']
- file: 'public/assets/articles/edit-%{locale}.js'
  only: ['*.js.helpers.*', '*.js.date.*', '*.js.cookies.*', '*.js.views.header.*', '*.js.views.footer.*', '*.js.search.modal.*', '*.js.topic.*', '*.js.article.*', '*.js.tag.*', '*.js.user.*', '*.js.search.*', '*.js.bookmark.*', '*.js.comment.*', '*.js.form.*', '*.js.drop_zone.*', '*.js.selecter.*', '*.js.categorized_tag.*']

- file: 'public/assets/tags/index-%{locale}.js'
  only: ['*.js.helpers.*', '*.js.date.*', '*.js.cookies.*', '*.js.views.header.*', '*.js.views.footer.*', '*.js.search.modal.*', '*.js.topic.*', '*.js.article.*', '*.js.tag.*', '*.js.user.*', '*.js.search.*', '*.js.bookmark.*', '*.js.comment.*']
- file: 'public/assets/tags/show-%{locale}.js'
  only: ['*.js.helpers.*', '*.js.date.*', '*.js.cookies.*', '*.js.views.header.*', '*.js.views.footer.*', '*.js.search.modal.*', '*.js.topic.*', '*.js.article.*', '*.js.tag.*', '*.js.user.*', '*.js.search.*', '*.js.bookmark.*', '*.js.comment.*']
- file: 'public/assets/tags/new-%{locale}.js'
  only: ['*.js.helpers.*', '*.js.date.*', '*.js.cookies.*', '*.js.views.header.*', '*.js.views.footer.*', '*.js.search.modal.*', '*.js.topic.*', '*.js.article.*', '*.js.tag.*', '*.js.user.*', '*.js.search.*', '*.js.bookmark.*', '*.js.comment.*', '*.js.form.*', '*.js.drop_zone.*', '*.js.selecter.*', '*.js.categorized_tag.*']
- file: 'public/assets/tags/edit-%{locale}.js'
  only: ['*.js.helpers.*', '*.js.date.*', '*.js.cookies.*', '*.js.views.header.*', '*.js.views.footer.*', '*.js.search.modal.*', '*.js.topic.*', '*.js.article.*', '*.js.tag.*', '*.js.user.*', '*.js.search.*', '*.js.bookmark.*', '*.js.comment.*', '*.js.form.*', '*.js.drop_zone.*', '*.js.selecter.*', '*.js.categorized_tag.*']

- file: 'public/assets/users/show-%{locale}.js'
  only: ['*.js.helpers.*', '*.js.date.*', '*.js.cookies.*', '*.js.views.header.*', '*.js.views.footer.*', '*.js.search.modal.*', '*.js.topic.*', '*.js.article.*', '*.js.tag.*', '*.js.user.*', '*.js.search.*', '*.js.bookmark.*', '*.js.comment.*']
- file: 'public/assets/users/profile-%{locale}.js'
  only: ['*.js.helpers.*', '*.js.date.*', '*.js.cookies.*', '*.js.views.header.*', '*.js.views.footer.*', '*.js.search.modal.*', '*.js.topic.*', '*.js.article.*', '*.js.tag.*', '*.js.user.*', '*.js.search.*', '*.js.bookmark.*', '*.js.comment.*']

- file: 'public/assets/admin/admin-%{locale}.js'
  only: ['*.js.helpers.*', '*.js.date.*', '*.js.cookies.*', '*.js.views.header.*', '*.js.views.footer.*', '*.js.search.modal.*', '*.js.topic.*', '*.js.article.*', '*.js.tag.*', '*.js.user.*', '*.js.search.*', '*.js.bookmark.*', '*.js.comment.*', '*.js.form.*', '*.js.drop_zone.*', '*.js.selecter.*', '*.js.categorized_tag.*', '*.js.admin.*']

- file: 'spec/javascripts/translations/translations-%{locale}.js'
