fallbacks: true
js_extend: false
sort_translation_keys: false

export_i18n_js: 'app/assets/javascripts/modules'

translations:
- file: 'public/assets/home-%{locale}.js'
  only: ['*.js.views.*', '*.js.topic.*', '*.js.article.*', '*.js.tag.*', '*.js.user.*', '*.js.search.*', '*.js.bookmark.*', '*.js.cookies.*', '*.js.helpers.*', '*.js.metrics.*', '*.js.date.*', '*.js.checkbox.*']

#- file: 'public/assets/articles/show-%{locale}.js'
#  only: ['*.js.helpers.*', '*.js.cookies.*', '*.js.search.modal.*', '*.js.user.*', '*.js.date.*', '*.js.article.*', '*.js.metrics.*', '*.js.comment.*', '*.js.bookmark.*']
#- file: 'public/assets/articles/new-%{locale}.js'
#  only: ['*.js.helpers.*', '*.js.cookies.*', '*.js.search.modal.*', '*.js.user.*', '*.js.date.*', '*.js.article.*', '*.js.metrics.*', '*.js.form.*', '*.js.drop_zone.*', '*.js.selectize.*', '*.js.categorized_tag.*']
#- file: 'public/assets/articles/edit-%{locale}.js'
#  only: ['*.js.helpers.*', '*.js.cookies.*', '*.js.search.modal.*', '*.js.user.*', '*.js.date.*', '*.js.article.*', '*.js.metrics.*', '*.js.form.*', '*.js.drop_zone.*', '*.js.selectize.*', '*.js.categorized_tag.*']
#
#- file: 'public/assets/tags/index-%{locale}.js'
#  only: ['*.js.helpers.*', '*.js.cookies.*', '*.js.search.modal.*', '*.js.user.*', '*.js.date.*', '*.js.tag.*', '*.js.metrics.*', '*.js.comment.*', '*.js.bookmark.*']
#- file: 'public/assets/tags/show-%{locale}.js'
#  only: ['*.js.helpers.*', '*.js.cookies.*', '*.js.search.modal.*', '*.js.user.*', '*.js.date.*', '*.js.tag.*', '*.js.metrics.*', '*.js.comment.*', '*.js.bookmark.*']
#- file: 'public/assets/tags/new-%{locale}.js'
#  only: ['*.js.helpers.*', '*.js.cookies.*', '*.js.search.modal.*', '*.js.user.*', '*.js.date.*', '*.js.tag.*', '*.js.metrics.*', '*.js.form.*', '*.js.drop_zone.*', '*.js.selectize.*', '*.js.categorized_tag.*']
#- file: 'public/assets/tags/edit-%{locale}.js'
#  only: ['*.js.helpers.*', '*.js.cookies.*', '*.js.search.modal.*', '*.js.user.*', '*.js.date.*', '*.js.tag.*', '*.js.metrics.*', '*.js.form.*', '*.js.drop_zone.*', '*.js.selectize.*', '*.js.categorized_tag.*']
#
#- file: 'public/assets/users/show-%{locale}.js'
#  only: ['*.js.helpers.*', '*.js.cookies.*', '*.js.search.modal.*', '*.js.user.*', '*.js.comment.*', '*.js.bookmark.*']
#- file: 'public/assets/users/profile-%{locale}.js'
#  only: ['*.js.helpers.*', '*.js.cookies.*', '*.js.search.modal.*', '*.js.user.*', '*.js.comment.*', '*.js.bookmark.*']
#
#- file: 'public/assets/admin/admin-%{locale}.js'
#  only: ['*.js.helpers.*', '*.js.cookies.*', '*.js.search.*', '*.js.admin.*', '*.js.user.*', '*.js.date.*', '*.js.article.*', '*.js.tag.*', '*.js.error_message.*', '*.js.selectize.*', '*.js.drop_zone.*']
