clean_uploads:
  cron: "*/30 * * * *" # execute at every 30 minutes
  class: "UploadsWorker"
  queue: default

remove_unused_tags:
  cron: "0 1 * * *" # execute at every day at 1 am
  class: "UnusedTagsWorker"
  queue: default
