---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
demo:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - [inrailsweblog_high, 2]
  - inrailsweblog_default
  - inrailsweblog_carrierwave
